#########################################################################
# brand_replacement        browser brand, e.g. IE, Chrome, Firefox, Opera
#                          default value is "family_replacement"

# family_replacement       browser family name, e.g. Chrome, Mobile Chrome
#                          default value is Group 1

# v1_replacement           version .
#                          default value is Group 2
##########################################################################


##########
# App WeChat
##########
- regex: '(micromessenger)/(\d+\.\d+)(\.(\d+))?'
  family_replacement: 'Wechat'
- regex: '(micromessenger)'
  family_replacement: 'Wechat'


##########
# Baidu Browsers (desktop spoofs chrome & IE, explorer is mobile)
##########
- regex: '(baidubrowser|baiduspider)/(\d+\.\d+)(\.(\d+))?'
  family_replacement: 'Baidu'
- regex: '(flyflow)/(\d+\.\d+)'
  brand_replacement: 'Baidu'
- regex: '(bidubrowser)[/ ](\d+\.\d+)(\.(\d+))?'
  family_replacement: 'Baidu'
- regex: '(biduplayerbrowser)[/ ](\d+\.\d+)'
  brand_replacement: 'Baidu'
  family_replacement: 'Baidu Player'
- regex: '(baiduboxapp|baiduboxpad)/(\d+\.\d+)(\.(\d+))* \(Baidu;'
  family_replacement: 'Baidu'
- regex: '(baiduboxapp)/(\d+\_\d+)(\.(\d+))?'
  family_replacement: 'Baidu'
###########
# UC Browser
# http://www.uc.cn/download/UCBrowser_User_Agent.pdf
###########
- regex: '(uc browser|ucbrowser|ucweb)[ /]?(\d+\.\d+)(\.(\d+))?'
  family_replacement: 'UC'
- regex: '(ubrowser)/(\d+\.\d+)'
  brand_replacement: 'UC'

###########
# Xiaomi MiuiBrowser
###########
- regex: '(miuibrowser)/(\d+\.\d+)(\.(\d+))?'
  family_replacement: 'MiuiBrowser'

##########
# 360 Explorer
##########
# 360 Safe Explorer : 360SE
# 360 Extreme Explorer: 360EE
# BIG PROBLEM:
# The lastest 360 Explorer fakes their UA to be Chrome, due to NI DONG DE
# CNZZ shows 360 Explorer has more than 20% market share, which I think is reasonable,
# however, Baidu tongji shows only 1.5%
# http://www.zhihu.com/question/20556578

- regex: '(360se)[ /](\d+\.\d+)'
  brand_replacement: '360'
- regex: '(360[se]e)'
  brand_replacement: '360'
  family_replacement: '360Browser'
- regex: '(theworld|the world)'
  brand_replacement: '360'
  family_replacement: 'TheWorld'


#########
# 360
# must come before Chrome
##########
# 360SE
# v5 fakes IE, which definitely no way to identify
# v6.0 fakes Chrome 20.0.1132.57
# v6.1, v6.2, v6.5 fake Chrome 21.0.1180.89
# v7 fakes Chrome/31.0.1650.63
# v8 fakes Chrome/42.0.2311.152
# Fortunately 360SE doesn't update as frequently as Chrome, maybe we could use this signature

- regex: '(chrome/42.0.2311.152)'
  brand_replacement: '360'
  family_replacement: '360SE v8'

- regex: '(chrome/31.0.1650.63)'
  brand_replacement: '360'
  family_replacement: '360SE v7'

- regex: '(chrome/20.0.1132.57|Chrome/21.0.1180.89)'
  brand_replacement: '360'
  family_replacement: '360SE v6'

# 360EE
# v7.0, v7.1 fake Chrome/24.0.1312.57
# v7.3 fakes Chrome/26.0.1410.64
# v7.5 fakes Chrome/30.0.1599.69

- regex: '(chrome/45.0.2454.101)'
  brand_replacement: '360'
  family_replacement: '360EE v8'

- regex: '(chrome/24.0.1312.57|Chrome/26.0.1410.64)'
  brand_replacement: '360'
  family_replacement: '360EE v7'
##########
# Sogou Explorer
###########
# SE 2.X MetaSr 1.0
- regex: '(se) (\d)\.x metasr'
  family_replacement: 'Sogou'

# does "SE 2.x" belong to Sogou
- regex: '(se) (\d)\.[xx]'
  family_replacement: 'Sogou'
- regex: '(sohunews)/(\d+\.\d+)(\.(\d+))?'
  brand_replacement: 'SohuNews'
  family_replacement: 'SohuNews Mobile'
## GIONEE  金立信
- regex: '(gionee)'
  brand_replacement: 'GIONEE'
  family_replacement: 'GIONEE Mobile'

- regex: '(sogoumobilebrowser)[ |/]?([\d|.]*)'
  family_replacement: 'Sogou'
  brand_replacement: 'Sogou'

- regex: '(sogoumse|sogousearch|sogouminimsesdk)'
  family_replacement: 'Sogou'
  brand_replacement: 'Sogou'

##########
# QQ Browser
# http://cooperate.qq.com/manage_notice_detail.jsp?id=42
##########
- regex: '(mqqbrowser|qqmusic)/(\d+\.\d+)(\.(\d+))?'
  brand_replacement: 'QQ'
  family_replacement: 'QQ Mobile'
- regex: '(qqbrowser)/(\d+\.\d+)'
  family_replacement: 'QQ'
- regex: '(qqlivebrowser|qqlivehdbrowser)/(\d+\.\d+)'
  brand_replacement: 'QQ'
  family_replacement: 'QQ Live'
- regex: '(tencenttraveler)/(\d+\.\d+)'
  brand_replacement: 'QQ'
##########
# LieBao Browser
##########
- regex: 'liebaofast/(\d+\.\d+)?'
  family_replacement: 'LieBao'
- regex: 'liebao|lbbrowser|liebaofast'
  family_replacement: 'LieBao'


# OppoBrowser
- regex: '(oppobrowser)/V(\d+\.\d+)(\.(\d+))?'
  family_replacement: 'OppoBrowser'

- regex: '(oppobrowser)/(\d+\.\d+)(\.(\d+))?'
  family_replacement: 'OppoBrowser'

#########
# EUI browser
########
- regex: '(eui browser)/(\d+\.\d+)'
  family_replacement: 'EUI browser'

#########
# LeBrowser
########
- regex: '(lebrowser)/(\d+\.\d+)(\.(\d+))?'
  family_replacement: 'LeBrowser'

#########
# MZBrowser
########
- regex: '(mzbrowser)/(\d+\.\d+)(\.(\d+))?'
  family_replacement: 'MZBrowser'
#########
# VivoBrowser
########
- regex: '(vivobrowser)/(\d+\.\d+)'
  family_replacement: 'VivoBrowser'

#########
# SamsungBrowser
########
- regex: '(samsungbrowser)/(\d+\.\d+)'
  brand_replacement: 'Samsung'
#######
# Others
######
- regex: '(airmail|barca|eudora|gcmail|lotus-notes|pocomail|postbox|shredder|sparrow|spicebird|the bat!|gcmail browser)[ /](\d+)\.?(\d+)?'

##########
# Firefox
##########
- regex: '(pale[mm]oon)/(\d+\.\d+)'
  brand_replacement: 'Firefox'
  family_replacement: 'Pale Moon'

- regex: '(fennec)/(\d+\.\d+)'
  brand_replacement: 'Firefox'
  family_replacement: 'Firefox Mobile'

- regex: 'mobile.*(firefox)/(\d+\.\d+)'
  brand_replacement: 'Firefox'
  family_replacement: 'Firefox Mobile'
- regex: '(firefox)/(\d+\.\d+)'
  brand_replacement: 'Firefox'
  family_replacement: 'Firefox Mobile'

- regex: '(namoroka|shiretoko|minefield)/(\d+\.\d+)\.(\d+(?:pre)?)'
  brand_replacement: 'Firefox'
- regex: '(namoroka|shiretoko|minefield)/(\d+\.\d+)([ab]\d+[a-z]*)?'
  brand_replacement: 'Firefox'

# Firefox alpha or beta version
- regex: '(firefox)/(\d+\.\d+)([ab]\d+[a-z]*)'

- regex: '(firefox)-(?:\d+\.\d+)?/(\d+\.\d+)([ab]\d+[a-z]*)'

- regex: '(firefox).*tablet browser (\d+\.\d+)\.(\d+)'
- regex: '(mozilladeveloperpreview)/(\d+\.\d+)([ab]\d+[a-z]*)?'
  brand_replacement: 'Firefox'

##########
# Opera
##########
# Opera will stop at 9.80 and hide the real version in the Version string.
# see: http://dev.opera.com/articles/view/opera-ua-string-changes/
- regex: '(opera tablet).*version/(\d+\.\d+)(?:\.(\d+))?'
  brand_replacement: 'Opera'

- regex: '(opera)/.+opera mobi.+version/(\d+\.\d+)'
  brand_replacement: 'Opera'
  family_replacement: 'Opera Mobile'

- regex: 'opera mobi'
  brand_replacement: 'Opera'
  family_replacement: 'Opera Mobile'

- regex: '(opera mini)/(\d+\.\d+)'
  brand_replacement: 'Opera'

- regex: '(opera mini)/att/(\d+\.\d+)'
  brand_replacement: 'Opera'

- regex: '(opera)/9.80.*version/(\d+\.\d+)(?:\.(\d+))?'

# Opera 14 for Android uses a WebKit render engine.
- regex: '(?:mobile safari).*(opr)/(\d+\.\d+)\.(\d+)'
  brand_replacement: 'Opera'
  family_replacement: 'Opera Mobile'
# Opera 15 for Desktop is similar to Chrome but includes an "OPR" Version string.
- regex: '(?:chrome).*(opr)/(\d+\.\d+)\.(\d+)'
  family_replacement: 'Opera'



##########
# IE Mobile
##########
- regex: '(iemobile)[ /](\d+)\.(\d+)'
  brand_replacement: 'IE'
  family_replacement: 'IE Mobile'
# desktop mode
# http://www.anandtech.com/show/3982/windows-phone-7-review
- regex: '(msie) (\d+)\.(\d+).*xblwp7'
  brand_replacement: 'IE'
  family_replacement: 'IE Large Screen'
##########
# Chrome Mobile
##########
- regex: '(crmo)/(\d+\.\d+\.\d+\.\d+)'
  brand_replacement: 'Chrome'
  family_replacement: 'Chrome Mobile'
- regex: '(crios)/(\d+\.\d+\.\d+\.\d+)'
  brand_replacement: 'Chrome'
  family_replacement: 'Chrome Mobile iOS'
- regex: '(chrome)/(\d+\.\d+\.\d+\.\d+) Mobile'
  brand_replacement: 'Chrome'
  family_replacement: 'Chrome Mobile'

# Chrome Frame must come before MSIE.
- regex: '(chromeframe)/(\d+\.\d+\.\d+)'
  brand_replacement: 'IE'
  family_replacement: 'Chrome Frame'





##########
# Mobile Safari
##########
- regex: '(ipod).*version/(\d+\.\d+)'
  brand_replacement: 'Safari'
  family_replacement: 'Safari Mobile'
- regex: '(iphone).*version/(\d+\.\d+)'
  brand_replacement: 'Safari'
  family_replacement: 'Safari Mobile'
- regex: '(ipad).*version/(\d+\.\d+)'
  brand_replacement: 'Safari'
  family_replacement: 'Safari Mobile'
- regex: '(ipod|iphone|ipad);.*cpu.*os (\d+)(?:_\d+)?_(\d+).*mobile'
  brand_replacement: 'Safari'
  family_replacement: 'Safari Mobile'
- regex: '(ipod|iphone|ipad)'
  brand_replacement: 'Safari'
  family_replacement: 'Safari Mobile'

##########
# Safari
##########
- regex: '(version)/(\d+\.\d+)(?:\.(\d+))?.*safari/'
  family_replacement: 'Safari'
# Safari didn't provide "Version/d.d.d" prior to 3.0
- regex: '(safari)/(\d+)'

